include ../common.mk

CXX=clang++

ifeq ($(HAS_CPP14), yes)
examples: \
	example_binary_literals_cpp14 \
	example_constexpr_cpp14 \
	example_decltype_auto_cpp14 \
	example_deprecated_attribute_cpp14 \
	example_generic_lambda_cpp14 \
	example_lambda_capture_cpp14 \
	example_lambda_capture_generator_cpp14 \
	example_lambda_capture_reference_cpp14 \
	example_lambda_capture_unique_cpp14 \
	example_return_type_deduction_cpp14 \
	example_variable_templates_cpp14
endif

